### ISSUE TITLE
[Request For Deploy] To account for new exercise UUIDs

### ISSUE THREAD

**Issue by nywilken** [exercism/trackler#81]
@kytrinyx just trying to put this on your radar. I am currently working through the tracks to repair the bogus UUIDs that were generated by Configlet. There are a number of tracks with bad UUIDs so the PRs are still trickling in. All the PRs link back to exercism/configlet#99 so we should be able to keep track of things there.

Once all PRs have been merged I suspect that a new trackler build, with the latest track configs, will be needed in order for the UUIDs to take effect. Please let me know if I am missing anything. 

Thanks!!!

**Comment by kytrinyx** [comment]
@nywilken thank you so much for picking this whole process up, and keeping it moving forward!

I will try to deploy daily. There's something new and weird in my development environment with node/javascript. It's something that has to do with work, but it's causing my Exercism deploy script to fail, so I end up having to do manual steps... which means I often end up not deploying.

We will need to do a full database refresh in v2 where the UUIDs are taken into account, but we need to do that anyway because of other things, so I don't think there's anything you have to worry about there.

**Comment by nywilken** [comment]
@kytrinyx I’m always happy to help. Glad to hear that a db refresh is already planned, I wasn’t 100% sure what the next steps were so thanks for the additional info. 

> I will try to deploy daily. There's something new and weird in my development environment with node/javascript. It's something that has to do with work, but it's causing my Exercism deploy script to fail, so I end up having to do manual steps... which means I often end up not deploying.

I know how that goes 😤. I hope it’s nothing too crazy. There is definitely no pressure on getting things out, this issue was more for me to confirm that no steps were being missed. I’ll keep chugging along with the UUID fixes.
